# Dependencies
markdown: kramdown

kramdown:
  input: GFM

pygments: false

# Permalinks
permalink: '/announcements/:title'

# Setup
title: OxyPlot
description: 'A cross-platform plotting library for .NET'
url: http://oxyplot.org

author:
  name: 'OxyPlot'
  url: http://oxyplot.org

paginate: 5
paginate_path: '/announcements/:num'

# Custom vars
version: 2015.1
docs: http://docs.oxyplot.org/
forum: http://discussion.oxyplot.org/
nuget: http://www.nuget.org/packages?q=oxyplot
myget: https://www.myget.org/feed/Packages/oxyplot
examples: https://github.com/oxyplot/oxyplot/tree/develop/Source/Examples/
twitter: http://twitter.com/search?q=oxyplot
so: http://stackoverflow.com/questions/tagged/oxyplot?sort=newest
chat: https://gitter.im/oxyplot/oxyplot

github:
  repo: http://github.com/oxyplot/oxyplot/
